"""add_source_watchpath_and_watched_files

Revision ID: cac992dd33a5
Revises: e35c49ccb454
Create Date: 2026-03-01 21:41:24.505787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac992dd33a5'
down_revision: Union[str, Sequence[str], None] = 'e35c49ccb454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watched_files_file_path'), 'watched_files', ['file_path'], unique=True)
    op.add_column('documents', sa.Column('source', sa.String(length=50), server_default='upload', nullable=False))
    op.add_column('documents', sa.Column('watch_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'watch_path')
    op.drop_column('documents', 'source')
    op.drop_index(op.f('ix_watched_files_file_path'), table_name='watched_files')
    op.drop_table('watched_files')
    # ### end Alembic commands ###
